/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carSeller;

/**
 *
 * @author HP
 */
public class CarSeller extends javax.swing.JFrame {

    /**
     * Creates new form CarSeller
     */
    public CarSeller() {
        initComponents();
        setTitle("Car Seller");
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgTransmission = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbxProductionYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbAutomatic = new javax.swing.JRadioButton();
        rbManual = new javax.swing.JRadioButton();
        chkAirCondition = new javax.swing.JCheckBox();
        btnPrice = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Production year:");

        cbxProductionYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016" }));
        cbxProductionYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProductionYearItemStateChanged(evt);
            }
        });

        jLabel2.setText("Transmission:");

        rbgTransmission.add(rbAutomatic);
        rbAutomatic.setSelected(true);
        rbAutomatic.setText("Automatic");

        rbgTransmission.add(rbManual);
        rbManual.setText("Manual");
        rbManual.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbManualItemStateChanged(evt);
            }
        });

        chkAirCondition.setText("Air Condition");

        btnPrice.setText("Price");
        btnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceActionPerformed(evt);
            }
        });

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxProductionYear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAutomatic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbManual))
                    .addComponent(chkAirCondition)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPrice)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnNewOrder))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProductionYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbAutomatic)
                    .addComponent(rbManual))
                .addGap(18, 18, 18)
                .addComponent(chkAirCondition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrice)
                    .addComponent(btnNewOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbManualItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbManualItemStateChanged
        if (rbManual.isSelected()) {
            chkAirCondition.setSelected(false);
            chkAirCondition.setEnabled(false);
        } else {
            chkAirCondition.setEnabled(true);
        }
    }//GEN-LAST:event_rbManualItemStateChanged

    private void cbxProductionYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductionYearItemStateChanged
        if (cbxProductionYear.getSelectedItem().equals("2014")) {
            rbManual.setEnabled(true);
        } else {
            rbManual.setEnabled(false);
            rbAutomatic.setSelected(true);
        }
        chkAirCondition.setSelected(false);
    }//GEN-LAST:event_cbxProductionYearItemStateChanged

    private void btnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceActionPerformed
        int price = 0;
        switch (cbxProductionYear.getSelectedItem().toString()) {
            case "2014":
                price = 10000;
                break;
            case "2015":
                price = 12000;
                break;
            case "2016":
                price = 14000;
                break;
        }
        if(rbAutomatic.isSelected()){
            price += 2000;
        }
        if(chkAirCondition.isSelected()){
            price += 1000;
        }
        lblPrice.setText("Price: " + price + "$");
        cbxProductionYear.setEnabled(false);
        rbAutomatic.setEnabled(false);
        rbManual.setEnabled(false);
        chkAirCondition.setEnabled(false);
        btnPrice.setEnabled(false);
        lblPrice.setVisible(true);
    }//GEN-LAST:event_btnPriceActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        cbxProductionYear.setEnabled(true);
        rbAutomatic.setEnabled(true);
        rbManual.setEnabled(true);
        chkAirCondition.setEnabled(true);
        btnPrice.setEnabled(true);
        lblPrice.setVisible(false);
        cbxProductionYear.setSelectedIndex(0);
        rbAutomatic.setSelected(true);
        chkAirCondition.setSelected(false);
    }//GEN-LAST:event_btnNewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnPrice;
    private javax.swing.JComboBox<String> cbxProductionYear;
    private javax.swing.JCheckBox chkAirCondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JRadioButton rbAutomatic;
    private javax.swing.JRadioButton rbManual;
    private javax.swing.ButtonGroup rbgTransmission;
    // End of variables declaration//GEN-END:variables
}
